FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG VERSION=dev
RUN go build \
    -ldflags="-s -w -X main.Version=${VERSION}" \
    -o /producer \
    ./cmd/producer

FROM scratch

COPY --from=builder /producer /producer

EXPOSE 9090 6060

ENTRYPOINT ["/producer"]
