{
 "title": "Tasks Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tasks by State",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tasks_produced_total", "legendFormat": "received" },
    { "expr": "tasks_processing_total", "legendFormat": "processing" },
    { "expr": "tasks_done_total", "legendFormat": "done" }
   ]
  },
  {
   "title": "Service State (Up/Down)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"producer\"}",
     "legendFormat": "Producer"
    },
    {
     "expr": "up{job=\"consumer\"}",
     "legendFormat": "Consumer"
    }
   ]
  },
  {
   "title": "Sum of Value per Task Type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tasks_value_sum_by_type_total", "legendFormat": "type {{type}}" }
   ]
  },
  {
   "title": "Processed Tasks per Task Type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tasks_by_type_total", "legendFormat": "type {{type}}" }
   ]
  }
 ]
}