prometheus_port: 9091
profiling_port: 6061
log_level: info
log_format: json

grpc_listen: ":50051"

rate_limit: 5
rate_burst: 20

db:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: tasks
  sslmode: disable
